"use client";

import Link from "next/link";
import { Bookmark, Copy, Heart, PencilLine, Share2, Users } from "lucide-react";
import { useState } from "react";
import { absoluteImageUrl, type WorkRecord } from "@/lib/work";

interface Permission { visibility: "PRIVATE" | "PUBLIC" | "PUBLIC_COLLAB"; allowEdit: boolean; allowFork: boolean; }
interface Contributor { userId: number; username: string; avatar: string | null; pixelCount: number; }
export default function ArtworkDetail({ artwork, username, avatar, permission, onlineCount, modificationCount, contributors }: { artwork: WorkRecord; username: string; avatar: string | null; permission: Permission; onlineCount: number; modificationCount: number; contributors: Contributor[] }) {
  const [saved, setSaved] = useState(false); const [liked, setLiked] = useState(false);
  const canCollaborate = permission.visibility === "PUBLIC_COLLAB" && permission.allowEdit;
  const share = async () => { await navigator.clipboard?.writeText(window.location.href); };
  return <section className="mx-auto max-w-6xl px-4 py-10 sm:px-8"><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><div><div className="overflow-hidden rounded-lg border border-white/[0.1] bg-[#11131c]"><div className="aspect-[4/3] bg-[linear-gradient(45deg,rgba(255,255,255,.03)_25%,transparent_25%,transparent_75%,rgba(255,255,255,.03)_75%)] bg-[length:18px_18px]">{(artwork.pixelImageUrl || artwork.sourceImageUrl) ? <img src={absoluteImageUrl(artwork.pixelImageUrl || artwork.sourceImageUrl) || undefined} alt={artwork.title} className="size-full object-contain [image-rendering:pixelated]" /> : null}</div></div><div className="mt-5 flex flex-wrap gap-2"><Link href={`/community/${artwork.id}/edit`} aria-disabled={!canCollaborate} className={`inline-flex h-10 items-center gap-2 border px-4 text-sm ${canCollaborate ? "border-cyan-400/60 bg-cyan-400/10 text-cyan-100 hover:bg-cyan-400/20" : "pointer-events-none border-white/[0.1] text-zinc-500"}`}><PencilLine className="size-4" />{canCollaborate ? "参与创作" : "仅展示"}</Link><button type="button" onClick={() => setSaved(!saved)} title="收藏作品" className={`grid size-10 place-items-center border ${saved ? "border-amber-300/60 text-amber-200" : "border-white/[0.14] text-zinc-300"}`}><Bookmark className="size-4" /></button><button type="button" onClick={() => setLiked(!liked)} title="点赞作品" className={`grid size-10 place-items-center border ${liked ? "border-rose-400/60 text-rose-300" : "border-white/[0.14] text-zinc-300"}`}><Heart className="size-4" /></button><button type="button" onClick={share} title="分享作品" className="grid size-10 place-items-center border border-white/[0.14] text-zinc-300"><Share2 className="size-4" /></button>{permission.allowFork && <Link href={`/editor?workId=${artwork.id}`} title="基于当前版本创建自己的作品" className="grid size-10 place-items-center border border-white/[0.14] text-zinc-300"><Copy className="size-4" /></Link>}</div></div>
    <aside className="border border-white/[0.1] bg-[#11131c] p-5"><p className="text-xs tracking-[0.18em] text-cyan-300">COMMUNITY ARTWORK</p><h1 className="mt-2 text-2xl font-semibold text-white">{artwork.title}</h1><div className="mt-5 flex items-center gap-3">{avatar ? <img src={absoluteImageUrl(avatar) || undefined} alt="作者头像" className="size-10 rounded-full object-cover" /> : <span className="grid size-10 place-items-center rounded-full bg-violet-600 text-sm font-semibold">{username.charAt(0).toUpperCase()}</span>}<div><p className="text-sm font-medium">{username}</p><p className="text-xs text-zinc-500">发布于 {artwork.publishedTime ? new Date(artwork.publishedTime).toLocaleDateString("zh-CN") : new Date(artwork.createTime).toLocaleDateString("zh-CN")}</p></div></div><dl className="mt-6 grid grid-cols-2 gap-3 border-y border-white/[0.1] py-4 text-sm"><div><dt className="text-zinc-500">在线创作者</dt><dd className="mt-1 flex items-center gap-1 text-cyan-200"><Users className="size-4" />{onlineCount}</dd></div><div><dt className="text-zinc-500">修改次数</dt><dd className="mt-1 text-white">{modificationCount}</dd></div></dl><div className="mt-5"><h2 className="text-sm font-medium">贡献者</h2><div className="mt-3 space-y-2">{contributors.length ? contributors.map((contributor) => <div key={contributor.userId} className="flex justify-between text-xs"><span className="text-zinc-300">{contributor.username}</span><span className="text-zinc-500">修改 {contributor.pixelCount} 像素</span></div>) : <p className="text-xs text-zinc-600">等待第一位协作者</p>}</div></div></aside></div></section>;
}
